###############################################################################
# supabase/config.toml
###############################################################################

# ─── remotes.preview : PR 用。deploy = false で本番は触らない ─────────
[remotes.preview]
project_id = "webfgicvknvldgsctvhl"   # Preview 用 ID
deploy     = false                    # ← ここがポイント

# ─── remotes.production : main ブランチにマージされたときだけ実行 ───
[remotes.production]
branch     = "main"                   # main への push でトリガー
project_id = "cpinzmlynykyrxdvkshl"   # 本番 ID
deploy     = true                     # デフォルトなので書かなくても OK