###############################################################################
# supabase/config.toml
###############################################################################

# ―― 本番プロジェクト（main にマージされたらここへ流れる） ―――――――――――
project_id = "cpinzmlynykyrxdvkshl"   # ← 本番 ID だけ残す

# ―― PR 用 Preview プロジェクト ―――――――――――――――――――――――――――――
[remotes.preview]
project_id = "webfgicvknvldgsctvhl"   # ← Preview 用 ID だけ