# SupabaseのバックアップをCI/CD で自動化（GitHub Actions）

name: Supabase Backup

on:
  schedule:
    # UTC 15,18,21,0,3,6,9,12 → JST 0,3,6,9,12,15,18,21
    - cron: '0 15,18,21,0,3,6,9,12 * * *'  # 3時間おき (JST ベース)
  workflow_dispatch:       # ← 追加：手動実行ボタン用

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'   # ジョブ内コマンドを JST 表示に
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Ensure backup directory exists
        run: mkdir -p hei-gakuseitenshoku/all_gakuseitenshoku
      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
      - name: Dump database
        run: |
          supabase link --project-ref "${{ secrets.SUPABASE_REF }}" \
                        --password    "${{ secrets.SUPABASE_DB_PASSWORD }}" \
                        --token       "${{ secrets.SUPABASE_ACCESS_TOKEN }}"
          supabase db dump --file hei-gakuseitenshoku/all_gakuseitenshoku/backup.sql
      - uses: actions/upload-artifact@v4
        with:
          name: supabase-backup
          path: hei-gakuseitenshoku/all_gakuseitenshoku/backup.sql