# SupabaseのバックアップをCI/CD で自動化（GitHub Actions）

name: Supabase Backup

on:
  schedule:
    - cron: '0 2 * * *'  # 毎日 2:00 JST

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: supabase/github-action@v1
        with:
          args: |
            link --project-ref ${{ secrets.SUPABASE_REF }} --password ${{ secrets.SUPABASE_DB_PASSWORD }}
            db dump --file=backup.sql
      - uses: actions/upload-artifact@v3
        with:
          name: supabase-backup
          path: backup.sql