# SupabaseのバックアップをCI/CD で自動化（GitHub Actions）

name: Supabase Backup

on:
  schedule:
    # UTC 15,18,21,0,3,6,9,12 → JST 0,3,6,9,12,15,18,21
    - cron: '0 15,18,21,0,3,6,9,12 * * *'  # 3時間おき (JST ベース)
  workflow_dispatch:       # ← 追加：手動実行ボタン用

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'   # ジョブ内コマンドを JST 表示に
      SUPABASE_ACCESS_TOKEN: ${{ secrets.BACKUP }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Ensure backup directory exists
        run: mkdir -p backups
      - name: Clean up old SQL backups
        run: |
          # Delete SQL files older than 30 days
          find backups -type f -name "data-*.sql" -mtime +30 -print -delete
      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
      - name: Dump database
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.BACKUP }}
        run: |
          supabase link --project-ref "${{ secrets.SUPABASE_REF }}" \
                        --password    "${{ secrets.SUPABASE_DB_PASSWORD }}"
          supabase db dump --data-only > backups/data-$(date +'%Y%m%d').sql
      - uses: actions/upload-artifact@v4
        with:
          name: supabase-backup
          path: backups/**/*.sql